# Generated by Django 5.1.2 on 2025-09-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=100)),
                ('weight', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, default='/static/images/phone.jpg', upload_to='images')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categories')),
            ],
        ),
    ]
